AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-ddb-workshop

Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/main.handler
      Runtime: nodejs14.x
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      Policies:
      - Statement:
        - Sid: DDBDescribeTablePolicy
          Effect: Allow
          Action:
          - dynamodb:DescribeTable
          Resource: !GetAtt 'DynamoDBTable.Arn'
  RecordVisitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/recordVisit.handler
      Runtime: nodejs14.x
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /tag/{tag}
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      Policies:
      - Statement:
        - Sid: DDBUpdateItemPolicy
          Effect: Allow
          Action:
          - dynamodb:UpdateItem
          Resource: !GetAtt 'DynamoDBTable.Arn'
  ViewCountsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/viewCounts.handler
      Runtime: nodejs14.x
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /counts/{tag}
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      Policies:
        - DynamoDBReadPolicy:
            TableName: 
              !Ref DynamoDBTable


  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"

Outputs:
  APIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  TableName:
    Description: "Name of the DynamoDB table"
    Value: !Ref DynamoDBTable

